### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by krypt0x** [Cache-core/Cache#5]
It's alright to copy and paste our code but you need to update the license to MIT. Please read our terms and conditions. Thank you.

![image](https://user-images.githubusercontent.com/35565671/104823459-13e82980-5842-11eb-8097-6ddf864e37cb.png)

**Comment by En4orcer** [comment]
https://github.com/Cache-core/Cache/blob/main/LICENSE.md This is our license.

If you look at the code, we have not removed/changed license headers, therefore this issue is invalid AFAICT.

**Comment by krypt0x** [comment]
The MIT license includes all the rights the GPL gives and more. And while people who receive your distribution only receive a GPL license to elements you added, they still receive an MIT license (from the original authors, not from you) to any elements contained in the work that the authors offered under that license.

It's technically legal. The MIT (Expat) license places a few restrictions on you. These are a subset of the GPL license. Therefore, if you relicense the code under the GPL, and keep the MIT notice, then you've satisfied the terms of the MIT license and may legally redistribute the code.

https://softwareengineering.stackexchange.com/questions/105912/can-you-change-code-distributed-under-the-mit-license-and-re-distribute-it-unde#:~:text=It's%20technically%20legal.,may%20legally%20redistribute%20the%20code.

**Comment by krypt0x** [comment]
All the best with your project. It's good to know there is people out there that appreciates our work. Thanks.
